[package]
name = "kyvo-example"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Example application built on top of the Ally SDK"
publish = false

[dependencies]
ally-sdk.workspace = true
ally-models.workspace = true
ally-plugins.workspace = true
ally-security.workspace = true
ally-events.workspace = true
ally-plugin-finance = { path = "../../plugins/finance" }
tokio.workspace = true
